### ISSUE TITLE
Can not set "maxmsgs" and "msgsize" when creating a message queue

### ISSUE THREAD

**Issue by delr** [mscdex/pmq#4]
ENOENT When creating a message queue with giving maxmsgs and msgsize.

The code snippet:

``` javascript
mq.open({
  name: '/testMQ',
  create: true,
  mode: '0777',
  maxmsgs: 20,
  msgsize: 1024
});
```

```
mq.open({
   ^
Error: no such file or directory
    at Object.<anonymous> (/home/adtop/workspace/atw-mockup/server/openMQ.js:6:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

**Comment by delr** [comment]
sorry, it was not an issue.
After setting `/proc/sys/fs/mqueue/msgsize_max` and `/proc/sys/fs/mqueue/msg_max`
it's working.
